behaviors:
  Troop1:
    trainer_type: poca
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0002
      beta: 0.005
      epsilon: 0.2
      lambd: 0.9
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 10000
    self_play:
      save_steps: 40000
      team_change: 200000
      swap_steps: 20000
      window: 10
      play_against_latest_model_ratio: 0.6
      initial_elo: 1200.0
  Troop2:
    trainer_type: poca
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0002
      beta: 0.005
      epsilon: 0.2
      lambd: 0.9
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 10000
    self_play:
      save_steps: 40000
      team_change: 200000
      swap_steps: 20000
      window: 10
      play_against_latest_model_ratio: 0.6
      initial_elo: 1200.0
